name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        rehash

    - name: Sync dependencies
      run: uv sync --locked

    - name: Lint
      run: uv run ruff check .

    - name: Typecheck
      run: uv run mypy src/

    - name: Test with coverage
      run: uv run pytest tests/ --cov=src --cov-report=term-missing --cov-fail-under=80

    - name: Build
      run: uv sync --dev